### ISSUE TITLE
How to add it to apple's Reminders?

### ISSUE THREAD

**Issue by suhaotian** [ryanburgess/2017-conferences#11]
I mean automation import

**Comment by ryanburgess** [comment]
Do you mean Apple's reminder app? Or Calendar?

**Comment by suhaotian** [comment]
Apple's reminder app

**Comment by ryanburgess** [comment]
I can look into it but I don't have plans on adding support of it yet. I'd also want to add support for Android if I was to add reminders for iOS.

**Comment by suhaotian** [comment]
Thank you 👍
